version: '3'
services:
  myapp:
    build:
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    restart: always
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/warehouse
  db:
    image: postgres
    environment:
      POSTGRES_DB: warehouse
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ifibat17
    restart: always
